[PHP]
; Augmente la limite de mémoire pour Symfony
memory_limit = 512M

; Augmente la taille max des fichiers uploadés
upload_max_filesize = 100M
post_max_size = 110M

; Augmente le temps d'exécution (10 minutes pour les petites machines)
max_execution_time = 600
max_input_time = 600

; Règle le fuseau horaire par défaut
date.timezone = Europe/Paris