[PHP]
; Augmente la limite de mémoire pour Symfony
memory_limit = 256M

; Augmente la taille max des fichiers uploadés (ex: 20 Mega-octets)
upload_max_filesize = 20M
post_max_size = 25M

; Règle le fuseau horaire par défaut
date.timezone = Europe/Paris