gesdinet_jwt_refresh_token:
    refresh_token_class: App\Entity\UserSession
    manager_type: orm
    ttl: 2592000 # 1 month
    ttl_update: true
    cookie:
        enabled: true
        same_site: lax
        path: /api/auth/refresh
        domain: null
        http_only: true
        secure: true
        remove_token_from_body: true
