lexik_jwt_authentication:
    secret_key: '%kernel.project_dir%/config/jwt/private.pem'
    public_key: '%kernel.project_dir%/config/jwt/public.pem'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: 1800 # 30 min
    token_extractors:
        authorization_header:
            enabled: true
            prefix:  Bearer
            name:    Authorization
        cookie:
            enabled: true
            name:    BEARER
    set_cookies:
        BEARER:
            lifetime: 1800
            samesite: lax
            path: /
            domain: null
            secure: '%env(bool:COOKIE_SECURE)%'
            httpOnly: true
