nelmio_api_doc:
    documentation:
        info:
            title: Organ API
            description: Project Management with Granular Permissions
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - Bearer: []
    areas:
        path_patterns:
            - ^/api(?!/doc$)
