server {
    listen 80;
    server_name localhost;
    
    # Le point d'entrée de Symfony est toujours le dossier /public
    root /var/www/html/public;
    index index.php;

    # Augmente la taille max autorisée par Nginx (doit être >= post_max_size de PHP)
    client_max_body_size 120M;

    location / {
        # Essaie de trouver le fichier, sinon redirige vers index.php (Front Controller)
        try_files $uri /index.php$is_args$args;
    }

    location ~ ^/index\.php(/|$) {
        # ATTENTION : C'est ici qu'on pointe vers le bon conteneur Docker !
        fastcgi_pass organ_api_php:9000;
        
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi_params;
        
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $realpath_root;

        # Augmente le timeout pour éviter les erreurs 504 (10 minutes)
        fastcgi_read_timeout 600;
        
        internal;
    }

    # Bloque l'accès direct aux autres fichiers PHP (sécurité)
    location ~ \.php$ {
        return 404;
    }

    error_log /var/log/nginx/project_error.log;
    access_log /var/log/nginx/project_access.log;
}