security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        api_user_provider:
            id: App\Security\ApiUserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            stateless: true
            custom_authenticator: App\Security\ExternalJwtAuthenticator
            entry_point: App\Security\ExternalJwtAuthenticator

            # On gère le logout manuellement dans le SecurityController pour appeler l'API


    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        # Pages publiques
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/about, roles: PUBLIC_ACCESS }
        - { path: ^/privacy, roles: PUBLIC_ACCESS }
        - { path: ^/$, roles: PUBLIC_ACCESS }
        - { path: ^/legal-notice, roles: PUBLIC_ACCESS }
        - { path: ^/privacy-policy, roles: PUBLIC_ACCESS }
        - { path: ^/terms, roles: PUBLIC_ACCESS }
        - { path: ^/get-the-app, roles: PUBLIC_ACCESS }

        # Tout le reste nécessite ROLE_USER (ex: /dashboard)
        - { path: ^/, roles: ROLE_USER }
